app:
  name: intask-backend
  version: 0.0.1
  env: ${APP_ENV}

server:
  http:
    addr: ${HTTP_ADDR}
    tls:
      enable: false
      server_cert_path: ./certs/server.crt
      server_key_path: ./certs/server.key
  conns:
    read_timeout: 2s
    write_timeout: 2s
    idle_timeout: 30s

# persistence is a set of settings
#
# it is used to define basic connection parameters,
# specify the host and port for the connection,
# and configure authentication settings
persistence:
  migrations_path: ./migrations/
  postgres:
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    sslmode: disable
    auth:
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      dbname: ${POSTGRES_DB}
    conns:
      max_idles: 15
      max_opens: 5
      max_lifetime: 15m
      max_idle_time: 30m

jwt:
  private_path: ./jwtRS256.key
  public_path: ./jwtRS256.key.pub
  token_ttl: 168h

workerpool:
  workers: 10
  task_buf: 20
  err_buf: 20

service:
  ticker_interval: 30s
  notificate_timeout: 6s